### ISSUE TITLE
allow path glob for template paths

### ISSUE THREAD

**Issue by StephanHCB** [StephanHCB/go-generator-lib#32]
Users have asked for the possibility to iterate over all files in a directory.

Can we maybe do something like this?

```
templates:
  - source: 'src/{{ .file }}'
    target: '{{ .file }}'
    with_files:
       - 'path/to/files/*.java'
       - 'path/to/files/*.md'
```

This should work in conjunction with `with_items` (nested loop), `condition`, and `just_copy`.
